name: Upload Lexicon

on:
  push:
    branches: ["main"]
    paths:
      - "**.pls"
      - ".github/**"

permissions: {}

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  upload:
    name: upload
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed to check out the repository
      id-token: write # Needed to authenticate against AWS
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }} # zizmor: ignore[secrets-outside-env] - TODO: Move to a dedicated environment
          aws-region: us-east-1
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Upload lexicon
        run: |
          aws polly put-lexicon --name mbtalexicon --content file://"${GH_WORKSPACE}"/mbtalexicon.pls
        env:
          GH_WORKSPACE: ${{ github.workspace }}
