name: Validate Lexicon

on:
  pull_request:
    paths:
      - "**.pls"
      - ".github/**"

permissions: {}

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    permissions:
      contents: read # Needed to check out the repository
      id-token: write # Needed to authenticate against AWS
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@cbe3b392738ccf3f987d68400dafcf4b0624a56c # v6.2.4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }} # zizmor: ignore[secrets-outside-env] - TODO: Move to a dedicated environment
          aws-region: us-east-1
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Validate lexicon
        run: |
          aws polly put-lexicon --name mbtalexiconvalidate --content file://"${GH_WORKSPACE}"/mbtalexicon.pls
        env:
          GH_WORKSPACE: ${{ github.workspace }}
